//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOGES_PM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cobro
    {
        public long IdCobro { get; set; }
        public int TipoCobro { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdEstadoCobro { get; set; }
        public double Monto { get; set; }
        public Nullable<long> IdProyecto { get; set; }
    
        public virtual Estado_Cobro Estado_Cobro { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual TipoCobro TipoCobro1 { get; set; }
    }
}
