//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOGES_PM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Correo
    {
        public long IdCorreo { get; set; }
        public string Asunto { get; set; }
        public string Cuerpo { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Remitente { get; set; }
        public long ClienteCorreo { get; set; }
        public bool Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
