//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOGES_PM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requerimiento_Proyecto
    {
        public long IdProyecto { get; set; }
        public long IdRequerimiento { get; set; }
        public long EmpleadoAsignado { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaLimite { get; set; }
    
        public virtual Proyecto Proyecto { get; set; }
        public virtual Requerimiento Requerimiento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
