//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISOGES_PM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Requerimiento_Proyecto = new HashSet<Requerimiento_Proyecto>();
        }
    
        public long IdUsuario { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Identificacion { get; set; }
        public string CorreoElectronico { get; set; }
        public string Telefono { get; set; }
        public int TipoUsuario { get; set; }
        public bool Estado { get; set; }
        public string Contrasena { get; set; }
        public Nullable<bool> PassIsTemp { get; set; }
        public Nullable<int> Puesto { get; set; }
    
        public virtual Puesto Puesto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requerimiento_Proyecto> Requerimiento_Proyecto { get; set; }
        public virtual TipoUsuario TipoUsuario1 { get; set; }
    }
}
